### ISSUE TITLE
Simple updates to README for people trying to use this project

### ISSUE THREAD

**Issue by plocher** [Weslex/rpi-led-flight-tracker#1]
Jumping in to build this - thanks for the fun project writeup!

I ran into two nits...

1) add: need to install the development tools for rtl-sdr:   

$ make
Package librtlsdr was not found in the pkg-config search path.
Perhaps you should add the directory containing `librtlsdr.pc'
to the PKG_CONFIG_PATH environment variable
Package 'librtlsdr', required by 'virtual:world', not found
cc -O2 -g -Wall -W  -c dump1090.c
dump1090.c:46:10: fatal error: rtl-sdr.h: No such file or directory
   46 | #include "rtl-sdr.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: dump1090.o] Error 1
$ sudo apt-get install librtlsdr-dev 

2) the requirements.txt in rpi-led-flight-tracker has an error:
$ pip install -r requirements.txt
ERROR: Invalid requirement: 'numpy=2.0.0' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
$ vi requirements.txt ... and change = to == :-)

  -John

**Comment by Weslex** [comment]
Thanks for pointing these issues out to me! I have corrected them. Please reach out if you have any other issues or get it running and would like to share!

**Comment by plocher** [comment]
One last bug - run-flight-tracker has two duplicate lines for
config.mapping_box_*height* and width (both say height) - if h != w then
the defaults are used instead of the value there.


Other than that, happiness!



  John
