### ISSUE TITLE
Chain order

### ISSUE THREAD

**Issue by ChopsKingsland** [Weslex/rpi-led-flight-tracker#2]
Is there a picture of the order that the panels were daisychained together?

**Comment by Weslex** [comment]
I followed the "U-mapper" arrangement of displays described in the rpi-led-rgb-matrix library. [U-mapper instructions](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#remapping-coordinates). 

Any mapping that works with the rpi-rgb-led-matrix should work. You just need to change `config.pixel_mapper_config = "U-mapper;Rotate:-90"` in run_flight_tracker.py if you are using a different arrangement.

**Comment by Weslex** [comment]
I noticed that your profile location is in the UK. Unfortunately, runways will not be displayed on the flight tracker outside of the US. Runways are drawn from a csv of runways published by the FAA so only US runways are included right now. Just a heads up.

**Comment by ChopsKingsland** [comment]
Thanks for the heads up. I have been trying for a while to get data like this for the UK, but haven't been able to find any. I'm now thinking of somehow getting the data from OpenStreetMap

**Comment by ChopsKingsland** [comment]
After a bit of research, I came across [ourairports.com](https://ourairports.com/), who have a runways.csv available for download that includes every runway in the world (I think, it at least contains the UK). I will write a python script at some point to filter the data and put it in the same format as the current runways.csv, and submit a PR with it in.

**Comment by ChopsKingsland** [comment]
@Weslex would just having airport code, lat1, lon1, lat2, lon2 work for UK airports or does this program require more info? From what I can work out in the code, it just needs the 2 sets of coords.

Edit: I can include edits to the code in the PR along with the airports if need be

**Comment by Weslex** [comment]
> @Weslex would just having airport code, lat1, lon1, lat2, lon2 work for UK airports or does this program require more info? From what I can work out in the code, it just needs the 2 sets of coords.
> 
> Edit: I can include edits to the code in the PR along with the airports if need be

Yes, the only values used to draw each runway are the latitude and longitude of the each end of the runway. The airport code isn't currently display. I found it adding it to the map cluttered the display. I should add it back as a feature the user can enable in the config though.

Switching to the runways.csv that you found should be simple. You will just have to ensure that le_latitude_deg, le_longitude_deg, he_latitude_deg, and he_longitude_deg are all not none before using a runway because some runways in that file appear to have missing data.

**Comment by ChopsKingsland** [comment]
I have created a PR with sanitised data. I would be grateful if you could try it because my displays haven’t arrived from aliexpress yet… #3 

Edit: I'm hoping my data includes US airports as well, so no other csv is needed

**Comment by Weslex** [comment]
> I have created a PR with sanitised data. I would be grateful if you could try it because my displays haven’t arrived from aliexpress yet… #3
> 
> Edit: I'm hoping my data includes US airports as well, so no other csv is needed

Sure! I will take a look at it. I think while you were working on that I tried adding support for your runways.csv file. It is in the new branch "intlrunways". Basically, I just added a flag so you can switch between using the FAA runways.csv or the ourairports csv. All you should have to change "config.use_intl_runways" to True and replace runways.csv with the ourairports.com csv. 

Here is an example of a static map of London I generated using that branch.
![london](https://github.com/user-attachments/assets/e6339ebd-1eec-41e4-9a49-2f1692063b2a)

I am actually waiting on displays from Aliexpress as well. I gave my first flight tracker to my father and I am waiting on the hardware to build another right now.

**Comment by ChopsKingsland** [comment]
Wow, the data actually works! Looks like I'll be implementing this as a permanent fixture when I get the displays. 

What power supply/driver board did you use by the way? I have a 5v 10a power supply and the Adafruit RGB Matrix Bonnet.

**Comment by Weslex** [comment]
> Wow, the data actually works! Looks like I'll be implementing this as a permanent fixture when I get the displays.
> 
> What power supply/driver board did you use by the way? I have a 5v 10a power supply and the Adafruit RGB Matrix Bonnet.

I used 2 5v 6A power supplies on my first one. Although for my second one I think I will try to use a single 10A or 12A power supplies. 

I have been using the GPIO pins on the raspberry pi to run the display. It works pretty well, but I think the bonnet would be a better solution. I will look into getting one. I do think you have to solder a jumper on the bonnet to get 64x64 displays to work.

I just found out that the rpi-rgb-led-matrix library doesn't currently support the raspberry pi 5, so I will have to order a new rpi4 as well.

**Comment by ChopsKingsland** [comment]
I didn't even realise you could drive it straight from the GPIO without a bonnet - quite cool!

I already soldered on a jumper (the one that disables the 3.5mm for PWM I think) for when I used a 32x64 matrix. I will look into the other one for the square matrices when mine turn up. 

Thank you for all your help!

**Comment by ChopsKingsland** [comment]
Sorry to keep asking questions. 

My displays arrived from AliExpress. When it came to hooking up power, did you wire them in series or parallel?

**Comment by Weslex** [comment]
> Sorry to keep asking questions. 
> 
> My displays arrived from AliExpress. When it came to hooking up power, did you wire them in series or parallel?

They are wired in parallel. You want every display to receive 5v.

**Comment by Weslex** [comment]
Were you able to get the flight tracker running?

**Comment by ChopsKingsland** [comment]
Yes I was, it works very well. Very good project! ![image](https://github.com/user-attachments/assets/61657035-8c12-40e1-bf91-705f84c8073e)

**Comment by Weslex** [comment]
> Yes I was, it works very well. Very good project! ![image](https://private-user-images.githubusercontent.com/18499854/369642947-61657035-8c12-40e1-bf91-705f84c8073e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTMzNzcsIm5iZiI6MTcyNzExMzA3NywicGF0aCI6Ii8xODQ5OTg1NC8zNjk2NDI5NDctNjE2NTcwMzUtOGMxMi00MGUxLWJmOTEtNzA1Zjg0YzgwNzNlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxNzM3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmI4ZGQ5NzE4OTcyZjExZDExY2Y0ZjE0OWViMmNkYWE0YTVkZmM3NWU4NjU2NTRiOWRlN2YzNWU2ZWQyYTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c3rBwx29krCSpUkMdFQ1WVyqfdEURO_9car_g16Xuy8)

Awesome that is great to hear! I recently got my new display up and running so I will be able to start making some improvements once again. Let me know if you have any problems or ideas to make the flight tracker better!
